window.BARRIER_DATABASE = {
    "metadata": {
        "source_file": "barrier data_updated.xlsx",
        "instruction": "This JSON file contains the exact data values extracted from the source Excel file organized by sheet name."
    },
    "data": {
        "Barrier data": [
            [
                "Barrier System",
                "Barrier System",
                "Accepted Test Level",
                "Type",
                "Anchor/Post Spacing (m) ",
                "Post/Pin Type ",
                "TMR Conditions (Speed)",
                "Test Speed (km/h)",
                "Width of barrier",
                "Tested Article Length (m) ",
                "Deflection (m)",
                "Working Width (m)",
                "Side slope limit ",
                "Available Lengths (m)",
                "Unit Weight (kg)",
                "Registered Supplier",
                "Austroads TCU Link",
                "Austroads TCU Link",
                "Manufacturers Specifications",
                "Manufacturers Specifications",
                "Image Link",
                "TMR Conditions",
                null
            ],
            [
                "Precast Concrete Barrier (PCB)",
                "Precast Concrete Barrier (PCB)",
                "Not Rated",
                "Concrete Single Slope",
                null,
                null,
                "Refer to Appendix B",
                "N/A",
                null,
                null,
                "N/A",
                "N/A",
                null,
                null,
                null,
                "Public Domain",
                "Public Domain ",
                null,
                null,
                null,
                null,
                null,
                null
            ],
            [
                "DB80 K150",
                "DB80 K150 Precast Concrete Barrier",
                "MASH TL-3",
                "Concrete F-Shape",
                "Freestanding",
                "NA",
                "Max 80 km/h",
                100,
                0.57,
                61.17,
                1.44,
                1.94,
                0.07,
                "2,4,6",
                "1200/ 2400 / 3600",
                "Jaybro Group Pty Ltd",
                "Austroads TCU - DB80 K150",
                "https://austroads.gov.au/__data/assets/pdf_file/0018/433206/210720-TCU-DB80-K150-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/16IUV3XTmltkXNjNTL1YT_5vemIMy1Nx4/view?usp=sharing",
                null,
                "https://drive.google.com/file/d/1He6YiftJ2tmgUqZaRaiky7Lj13Dd9GeW/view?usp=sharing",
                "This F shape temporary concrete barrier is only acceptable for use\non roads with speed limits of 80 km/h or less.",
                null
            ],
            [
                "DB80 T150S",
                "DB80 T150S Precast Concrete Barrier",
                "MASH TL-3",
                "Concrete F-Shape",
                "Anchored at ends only",
                "NA",
                "Max 80 km/h",
                100,
                0.57,
                92,
                0.81,
                1.36,
                0.1,
                "2,4,6",
                "1050 / 2100 /3150",
                "Jaybro Group Pty Ltd",
                "Austroads TCU - DB80 T150S",
                "https://austroads.gov.au/__data/assets/pdf_file/0034/467467/211220-TCU-DB80-T150-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1LLi9Qu3Hp4SGl71314N8pcmX-vN5PVon/view?usp=sharing",
                null,
                "https://drive.google.com/file/d/1OadXkTBwxFPa-2UCUmBkOoQdcg-dEcH8/view?usp=sharing",
                "This F shape temporary concrete barrier is only acceptable for use\non roads with speed limits of 80 km/h or less.",
                null
            ],
            [
                "DB80 T150S",
                "DB80 T150S Precast Concrete Barrier",
                "MASH TL-4",
                "Concrete F-Shape",
                "Anchored at ends only",
                "NA",
                "Max 80 km/h",
                100,
                0.57,
                92,
                0.81,
                2.5,
                0.1,
                "2,4,6",
                "1050 / 2100 /3150",
                "Jaybro Group Pty Ltd",
                "Austroads TCU - DB80 T150S",
                "https://austroads.gov.au/__data/assets/pdf_file/0034/467467/211220-TCU-DB80-T150-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1LLi9Qu3Hp4SGl71314N8pcmX-vN5PVon/view?usp=sharing",
                null,
                "https://drive.google.com/file/d/1OadXkTBwxFPa-2UCUmBkOoQdcg-dEcH8/view?usp=sharing",
                "This F shape temporary concrete barrier is only acceptable for use\non roads with speed limits of 80 km/h or less.",
                null
            ],
            [
                "DB80A T150S",
                "DB80A T150S Precast Concrete Barrier",
                "MASH TL3 (concrete installation) ",
                "Concrete F-Shape",
                3,
                "M20 x 380mm threaded rod with epoxy ",
                "Max 80 km/h",
                100,
                0.5700000000000001,
                68,
                0.34,
                0.91,
                0.1,
                "2,4,6",
                "1100 /2200 / 3300",
                "Jaybro Group Pty Ltd",
                "Austroads TCU - DB80A T150S",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/533846/221201-TCU-DB80A-T150-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1LoZmf0q3aMfYDrtxSn72_EtX7TyoAbwA/view?usp=sharing",
                null,
                "https://drive.google.com/file/d/1ko7r_WjAeIFatBYkKhgoBnZjKHv2RrPs/view?usp=sharing",
                "This F shape temporary concrete barrier is only acceptable for use\non roads with speed limits of 80 km/h or less.",
                null
            ],
            [
                "DB80A T150S",
                "DB80A T150S Precast Concrete Barrier",
                "MASH TL3 (asphalt installation) ",
                "Concrete F-Shape",
                3,
                "DB-Pin P600A",
                "Max 80 km/h",
                80,
                0.57,
                68,
                0.55,
                0.91,
                0.1,
                "2,4,6",
                "1100 /2200 / 3300",
                "Jaybro Group Pty Ltd",
                "Austroads TCU - DB80A T150S",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/533846/221201-TCU-DB80A-T150-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1LoZmf0q3aMfYDrtxSn72_EtX7TyoAbwA/view?usp=sharing",
                null,
                "https://drive.google.com/file/d/1ko7r_WjAeIFatBYkKhgoBnZjKHv2RrPs/view?usp=sharing",
                null,
                null
            ],
            [
                "JJ Hooks MASH",
                "JJ Hooks MASH Precast Concrete Barrier",
                "MASH TL-3",
                "Concrete F-Shape",
                "Freestanding",
                "NA",
                "Max 80 km/h",
                100,
                0.61,
                59,
                1.63,
                2.23,
                0.06,
                3.6,
                2600,
                "Australian Road Barriers",
                "3.6 Metre Barrier Unit",
                "https://austroads.gov.au/__data/assets/pdf_file/0025/480508/220314-TCU-3.6-M-JJ-Hooks-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1LUzvzR77MHrTHdq5TS7h2AnqIyhaYJHo/view?usp=sharing",
                null,
                "https://drive.google.com/file/d/1EIbMTzowiiRFkamM4QxSKcwV6Z4bfxu7/view?usp=sharing",
                "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.",
                null
            ],
            [
                "JJ Hooks MASH",
                "JJ Hooks MASH Precast Concrete Barrier",
                "MASH TL-3",
                "Concrete F-Shape",
                "Freestanding",
                "NA",
                "Max 80 km/h",
                100,
                0.6,
                66,
                1.6,
                2.2,
                0.06,
                6,
                4430,
                "Australian Road Barriers",
                "6 Metre Barrier Unit",
                "https://austroads.gov.au/__data/assets/pdf_file/0026/480509/220314-TCU-JJ-HOOKS-MASH-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1LUzvzR77MHrTHdq5TS7h2AnqIyhaYJHo/view?usp=sharing",
                null,
                "https://drive.google.com/file/d/1EIbMTzowiiRFkamM4QxSKcwV6Z4bfxu7/view?usp=sharing",
                null,
                null
            ],
            [
                "T-LOK",
                "T-LOK Precast Concrete Barrier",
                "MASH TL-3",
                "Concrete F-Shape",
                "Freestanding",
                "NA",
                "Max 80 km/h",
                100,
                0.6099999999999999,
                58.5,
                1.27,
                1.88,
                0.05,
                "3.6, 5.49",
                "2600, 3900",
                "Saferoads",
                "Austroads TCU - T-LOK",
                "https://austroads.gov.au/__data/assets/pdf_file/0019/570520/230601-TCU-T-LOK-MASH-F-TYPE-Concrete-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1TgaOsIO9LkAI4Xf7xC5RMVxdupqViQ8-/view?usp=sharing",
                null,
                "https://drive.google.com/file/d/1sEnks5qJT8QZWLw4ymZ8Pi9bRCrTvw8U/view?usp=sharing",
                "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.\nThe Bespoke Wedge is accepted for use where the speed limit is\nrestricted to 60 km/h or less.",
                null
            ],
            [
                "T-LOK Rubber",
                "T-LOK Rubber Precast Concrete Barrier",
                "MASH TL-3",
                "Concrete F-Shape",
                "Freestanding",
                "NA",
                "Max 80 km/h",
                100,
                0.6100000000000001,
                58.5,
                1.76,
                2.37,
                0.05,
                "3.6, 5.49",
                "2600, 3900",
                "Saferoads",
                "Austroads TCU - T-LOK Rubber",
                "https://austroads.gov.au/__data/assets/pdf_file/0020/570521/230601-TCU-T-LOK-Rubber-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1DJq-1-IW0DuIIs3Lde-Z8-5LScod1sms/view?usp=sharing",
                null,
                null,
                "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.\nThe Bespoke Wedge is accepted for use where the speed limit is\nrestricted to 60 km/h or less.",
                null
            ],
            [
                "Pin and Loop",
                "Pin and Loop Precast Concrete Barrier",
                "MASH TL-3",
                "Concrete F-Shape",
                "Freestanding",
                "NA",
                "Max 80 km/h",
                100,
                0.6100000000000001,
                61.4,
                1.61,
                2.22,
                0.07,
                "3.81, ",
                2640,
                "Pin and Loop Pty Ltd",
                "Austroads TCU - Pin and Loop",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/463434/211201-TCU-PIN-and-LOOP-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1R1y0ZOsw5ENT7FVCerx7YCRHVRYppuCm/view?usp=sharing",
                null,
                null,
                "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.",
                null
            ],
            [
                "BG800",
                "BG800 Steel Rail Safety Barrier",
                "MASH TL-3",
                "Steel",
                60,
                null,
                "Nil",
                100,
                0.5400000000000003,
                72,
                1.66,
                2.2,
                0.08,
                "6, 12",
                "540, 1080",
                "Ingal Civil Products",
                "BG800 Standard - Temporary:",
                "https://austroads.gov.au/__data/assets/pdf_file/0027/463455/211201-TCU-BG800-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/15X4jRGK0T1uSk2_wanHw-3p2pCm36HIx/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "BG800",
                "BG800 Steel Rail Safety Barrier",
                "MASH TL-4",
                "Steel",
                60,
                null,
                null,
                100,
                0.54,
                72,
                2.31,
                3.66,
                0.08,
                6,
                540,
                "Ingal Civil Products",
                "BG800 Standard - Temporary:",
                "https://austroads.gov.au/__data/assets/pdf_file/0027/463455/211201-TCU-BG800-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/15X4jRGK0T1uSk2_wanHw-3p2pCm36HIx/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "BG800",
                "BG800 MDS Steel Safety Barrier",
                "MASH TL-3",
                "Steel",
                6,
                "M24 x 250mm threaded rod with epoxy \n\nM24 x 450mm threaded rod with epoxy ",
                null,
                100,
                0.54,
                42,
                0.44,
                0.98,
                0.08,
                "6, 12",
                "540, 1080",
                "Ingal Civil Products",
                "BG800 MDS - Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0031/463459/211201-TCU-BG800-MDS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/15X4jRGK0T1uSk2_wanHw-3p2pCm36HIx/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "BG800",
                "BG800 LDS Steel Safety Barrier",
                "MASH TL-2",
                "Steel",
                12,
                "M24 x 460mm Threaded rod with epoxy ",
                null,
                80,
                0.54,
                72,
                0.42,
                0.96,
                0.08,
                "6, 12",
                "720, 1440",
                "Ingal Civil Products",
                "BG800 LDS - Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/463452/211201-TCU-BG800-LDS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/15X4jRGK0T1uSk2_wanHw-3p2pCm36HIx/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "HighwayGuard",
                "HighwayGuard Safety Barrier - Temporary",
                "MASH TL-3",
                "Steel",
                42,
                "figure out later",
                "Nil",
                100,
                0.54,
                108,
                1.71,
                2.25,
                0.08,
                "6, 12",
                "552, 1034",
                "Ingal Civil Products",
                "HighwayGuard Standard - Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/516552/220908-TCU-HIGHWAYGUARD-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1IH73E0qy5HBPJxKMVHMwDG86m828__di/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "HighwayGuard",
                "HighwayGuard Safety Barrier - Temporary",
                "MASH TL-3",
                "Steel",
                58,
                "figure out later",
                null,
                100,
                0.5400000000000003,
                120,
                1.93,
                2.47,
                0.08,
                "6, 12",
                "552, 1034",
                "Ingal Civil Products",
                "HighwayGuard Standard - Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/516552/220908-TCU-HIGHWAYGUARD-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1IH73E0qy5HBPJxKMVHMwDG86m828__di/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "HighwayGuard",
                "HighwayGuard Safety Barrier - Temporary",
                "MASH TL-4",
                "Steel",
                58,
                "figure out later",
                null,
                100,
                1.3499999999999996,
                120,
                2.16,
                3.51,
                0.08,
                "6, 12",
                "552, 1034",
                "Ingal Civil Products",
                "HighwayGuard Standard - Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/516552/220908-TCU-HIGHWAYGUARD-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1IH73E0qy5HBPJxKMVHMwDG86m828__di/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "HighwayGuard",
                "HighwayGuard LDS Safety Barrier - Temporary ",
                "MASH TL-3",
                "Steel",
                12,
                "M24 x 330mm threaded rod with epoxy\n(12 metre anchor spacing only) \nM24 x 450mm threaded rod with epoxy ",
                null,
                100,
                0.5399999999999999,
                60,
                0.68,
                1.22,
                0.08,
                "6, 12",
                "552, 1034",
                "Ingal Civil Products",
                "HighwayGuard LDS - Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/463448/211201-TCU-HIGHWAYGUARD-LDS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1DxqOzjGDg0E-u3Sou7OhkQMm5b-ZMRcr/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "HighwayGuard",
                "HighwayGuard LDS Safety Barrier - Temporary ",
                "MASH TL-3",
                "Steel",
                24,
                "M24 x 330mm threaded rod with epoxy\n(12 metre anchor spacing only) \nM24 x 450mm threaded rod with epoxy ",
                null,
                100,
                0.54,
                60,
                1.16,
                1.7,
                0.08,
                "6, 12",
                "552, 1034",
                "Ingal Civil Products",
                "HighwayGuard LDS - Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/463448/211201-TCU-HIGHWAYGUARD-LDS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1DxqOzjGDg0E-u3Sou7OhkQMm5b-ZMRcr/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "HighwayGuard",
                "HighwayGuard LDS Safety Barrier - Temporary ",
                "MASH TL-4",
                "Steel",
                24,
                "M24 x 330mm threaded rod with epoxy\n(12 metre anchor spacing only) \nM24 x 450mm threaded rod with epoxy ",
                null,
                100,
                1.72,
                84,
                1.16,
                2.88,
                0.08,
                "6, 12",
                "552, 1034",
                "Ingal Civil Products",
                "HighwayGuard LDS - Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/463448/211201-TCU-HIGHWAYGUARD-LDS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1DxqOzjGDg0E-u3Sou7OhkQMm5b-ZMRcr/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "HighwayGuard",
                "HighwayGuard MDS Safety Barrier - Temporary ",
                "MASH TL-3",
                "Steel",
                2,
                null,
                null,
                100,
                0.54,
                36,
                0.025,
                0.67,
                0.08,
                "6, 12",
                "552, 1034",
                "Ingal Civil Products",
                "HighwayGuard MDS - Temporary (TL-3):",
                "https://austroads.gov.au/__data/assets/pdf_file/0027/570528/230601-TCU-HIGHWAYGUARD-MDS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/11rYLXesmG7J5DFRjhtgntREugcFWgraP/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Defender Barrier",
                "DEFENDER Barrier 70 Steel Safety Barrier - Temporary  ",
                "MASH TL-2",
                "Steel",
                "Freestanding with ballast ",
                null,
                "Nil",
                70,
                0.6799999999999999,
                105,
                1.2,
                1.88,
                0.1,
                3.96,
                320,
                "Safe Barriers Pty. Ltd.",
                "Defender Barrier 70:",
                "https://austroads.gov.au/__data/assets/pdf_file/0028/463429/211201-TCU-DEFENDER-70-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1aCrUADHqr19hkjxji-N4w--e9W2uR0DX/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Defender Barrier",
                "DEFENDER Barrier 100 LDS Safety Barrier - Temporary",
                "MASH TL-3",
                "Steel",
                9.15,
                "Deep lift asphaltic concrete - M25 x 440mm threaded rod with epoxy \n\nAsphaltic concrete over granular pavement - M30 x 500mm asphalt pin ",
                null,
                100,
                0.68,
                78,
                0.88,
                1.56,
                0.1,
                3.96,
                303,
                "Safe Barriers Pty. Ltd.",
                "Defender Barrier 100 LDS",
                "https://austroads.gov.au/__data/assets/pdf_file/0022/444307/210903-TCU-DEFENDER-100-LDS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/13Wo4yxjNXB8kOdPWLt127KZFqCNIck7e/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Defender Barrier",
                "DEFENDER Barrier 100 HC Steel Safety Barrier - Temporary ",
                "MASH TL-3",
                "Steel",
                45.45,
                "M30 x 500mm asphalt pin",
                null,
                100,
                0.68,
                97.5,
                1.96,
                2.44,
                0.1,
                3.96,
                303,
                "Safe Barriers Pty. Ltd.",
                "Defender Barrier 100 HC:",
                "https://austroads.gov.au/__data/assets/pdf_file/0021/444306/210903-TCU-DEFENDER-100-HC-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1qLEugecOdtVCNOdUCgJ4jHqsmq7sGMDL/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Defender Barrier",
                "DEFENDER Barrier 100 HC Steel Safety Barrier - Temporary ",
                "MASH TL-3",
                "Steel",
                48.14,
                "M30 x 500mm asphalt pin",
                null,
                100,
                0.6800000000000002,
                97.5,
                2.3,
                2.98,
                0.1,
                3.96,
                303,
                "Safe Barriers Pty. Ltd.",
                null,
                "https://austroads.gov.au/__data/assets/pdf_file/0021/444306/210903-TCU-DEFENDER-100-HC-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1qLEugecOdtVCNOdUCgJ4jHqsmq7sGMDL/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Defender Barrier",
                "DEFENDER Barrier 100 HC Steel Safety Barrier - Temporary ",
                "MASH TL-4",
                "Steel",
                48.14,
                "M30 x 500mm asphalt pin",
                null,
                100,
                0.68,
                97.5,
                2.47,
                3.31,
                0.1,
                3.96,
                303,
                "Safe Barriers Pty. Ltd.",
                null,
                "https://austroads.gov.au/__data/assets/pdf_file/0021/444306/210903-TCU-DEFENDER-100-HC-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1qLEugecOdtVCNOdUCgJ4jHqsmq7sGMDL/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Defender Barrier",
                "DEFENDER 100 FS Safety Barrier - Temporary ",
                "MASH TL-3",
                "Steel",
                "Freestanding with ballast",
                null,
                null,
                100,
                0.68,
                156,
                1.9,
                2.58,
                0.1,
                3.96,
                320,
                "Safe Barriers Pty. Ltd.",
                "Defender Barrier 100 FS",
                "https://austroads.gov.au/__data/assets/pdf_file/0022/463432/211201-TCU-DEFENDER-100-FS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1uBaKX4oxNiaJX8KMsSlHShjXe1iK-HrX/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "SafeZone",
                "SAFEZONE Safety Barrier - Temporary  ",
                "MASH TL-3",
                "Steel",
                69.6,
                "figure out later",
                "Nil",
                100,
                0.454,
                69.6,
                1.7,
                2.06,
                0.08,
                "5.8,",
                464,
                "Jaybro Group Pty Ltd",
                "SafeZone Standard - Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0013/633100/240307-TCU-SafeZone-LDS-Safety-Barrier-Permanent-and-Temporary.pdf",
                "https://drive.google.com/file/d/1yoxc9f54tUAK6XUjY7kFGmVnFh_DeENV/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "SafeZone",
                "SAFEZONE Safety Barrier - Temporary  ",
                "MASH TL-4",
                "Steel",
                69.6,
                "figure out later",
                null,
                100,
                0.454,
                69.6,
                2.07,
                2.96,
                0.08,
                "5.8,",
                464,
                "Jaybro Group Pty Ltd",
                null,
                "https://austroads.gov.au/__data/assets/pdf_file/0013/633100/240307-TCU-SafeZone-LDS-Safety-Barrier-Permanent-and-Temporary.pdf",
                "https://drive.google.com/file/d/1yoxc9f54tUAK6XUjY7kFGmVnFh_DeENV/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "SafeZone",
                "SafeZone LDS Safety Barrier - Permanent & Temporary  ",
                "MASH TL-3",
                "Steel",
                11.6,
                "Concrete - M30 x 300mm threaded rod with  epoxy (TL4) or M30 x 175mm threaded rod with  epoxy (TL3 only) \n\nDeep lift asphaltic concrete - M30 x 300mm threaded rod with epoxy\n\nAsphaltic concrete over granular - M30 x 300mm threaded rod with epoxy ",
                null,
                100,
                0.64,
                40.6,
                0.42,
                1.06,
                0.08,
                "5.8, 11.6",
                "464, 1070",
                "Jaybro Group Pty Ltd",
                "SafeZone LDS - Permanent & Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/592643/230901-TCU-SAFEZONE-MDS-Safety-Barrier-Permanent-and-Temporary.pdf",
                "https://drive.google.com/file/d/1yoxc9f54tUAK6XUjY7kFGmVnFh_DeENV/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "SafeZone",
                "SafeZone LDS Safety Barrier - Permanent & Temporary  ",
                "MASH TL-4",
                "Steel",
                11.6,
                "Concrete - M30 x 300mm threaded rod with  epoxy (TL4) or M30 x 175mm threaded rod with  epoxy (TL3 only) \n\nDeep lift asphaltic concrete - M30 x 300mm threaded rod with epoxy\n\nAsphaltic concrete over granular - M30 x 300mm threaded rod with epoxy ",
                null,
                100,
                0.64,
                40.6,
                0.45,
                2.17,
                0.08,
                "5.8, 11.6",
                "464, 1070",
                "Jaybro Group Pty Ltd",
                null,
                "https://austroads.gov.au/__data/assets/pdf_file/0029/592643/230901-TCU-SAFEZONE-MDS-Safety-Barrier-Permanent-and-Temporary.pdf",
                "https://drive.google.com/file/d/1yoxc9f54tUAK6XUjY7kFGmVnFh_DeENV/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "SafeZone",
                "SAFEZONE MDS Safety Barrier - Permanent & Temporary ",
                "MASH TL-3",
                "Steel",
                5.8,
                "M30 x 300mm threaded rod with epoxy  ",
                null,
                100,
                0.639,
                40.6,
                0.17,
                0.81,
                0.08,
                5.8,
                464,
                "Jaybro Group Pty Ltd",
                "SafeZone MDS - Permanent & Temporary",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/592643/230901-TCU-SAFEZONE-MDS-Safety-Barrier-Permanent-and-Temporary.pdf",
                "https://drive.google.com/file/d/1yoxc9f54tUAK6XUjY7kFGmVnFh_DeENV/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "IronMan Hybrid MASH",
                "IRONMAN HYBRID Steel Safety Barrier - Temporary ",
                "MASH TL-2",
                "Steel",
                "freestanding",
                null,
                "Bespoke Wedge <=60",
                70,
                0.55,
                114.3,
                1.49,
                2.04,
                0.05,
                4.15,
                925,
                "Saferoads",
                "Austroads TCU - IronMan",
                "https://austroads.gov.au/__data/assets/pdf_file/0030/598620/230925-TCU-IRONMAN-HYBRID-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1UfcYtt6YNn4epy6depqvQRK3yVBm2XLb/view?usp=sharing",
                null,
                null,
                "The Bespoke Wedge is accepted for use where the speed limit is\nrestricted to 60 km/h or less.",
                null
            ],
            [
                "Zoneguard",
                "ZONEGUARD Steel Safety Barrier - Temporary",
                "MASH TL-3",
                "Steel",
                65,
                "Concrete - M30 x 300mm threaded rod with  epoxy \n\nDeep lift asphaltic concrete, Asphaltic concrete over granular pavement, Flush seal over granular pavement - M30 x 500mm\n\n ",
                "Nil",
                100,
                0.7000000000000002,
                75,
                1.9,
                2.6,
                0.07,
                "4.11, 11.85",
                "400, 1100",
                "Hill & Smith",
                "Zoneguard Standard",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/464981/211208-TCU-ZONEGUARD-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/11EFH9VYph2NLmm6ZfrO_Wt7NttYXs9XJ/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Zoneguard",
                "ZONEGUARD MDS Steel Safety Barrier - Temporary  ",
                "NCHRP 350 TL3 update (Concrete Installation)",
                "Steel",
                10.2,
                "M30 x 300mm treaded rod with epoxy ",
                null,
                100,
                0.7,
                95,
                0.13,
                0.83,
                0.07,
                "4.11, 11.85",
                "400, 1100",
                "Hill & Smith",
                "Zoneguard MDS",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/406985/210304-TCU-ZONEGUARD-MDS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/11EFH9VYph2NLmm6ZfrO_Wt7NttYXs9XJ/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Zoneguard",
                "ZONEGUARD MDS Steel Safety Barrier - Temporary  ",
                "MASH TL3 (Asphalt Installation) ",
                "Steel",
                6,
                "M30 x 500mm asphalt pin",
                null,
                100,
                0.7,
                95,
                0.1,
                0.8,
                0.07,
                "4.11, 11.85",
                "400, 1100",
                "Hill & Smith",
                "Zoneguard MDS",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/406985/210304-TCU-ZONEGUARD-MDS-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/11EFH9VYph2NLmm6ZfrO_Wt7NttYXs9XJ/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "HV2",
                "HV2 Steel and Concrete Longitudinal Barrier - Temporary",
                "MASH TL-3",
                "Steel",
                "Freestanding with ballast ",
                null,
                "Nil",
                100,
                0.45,
                98.6,
                1.47,
                1.84,
                0.05,
                5.8,
                2088,
                "Saferoads Pty Ltd",
                "Austroads TCU - HV2",
                "https://austroads.gov.au/__data/assets/pdf_file/0021/463440/211201-TCU-HV2-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1xejQnex0FC1FAkh_9XYnIbSJpu8JzLEr/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "HV2",
                "HV2 Steel and Concrete Longitudinal Barrier - Temporary",
                "MASH TL-4",
                "Steel",
                "Freestanding with ballast ",
                null,
                "Nil",
                100,
                0.45,
                278,
                2.37,
                3.74,
                0.05,
                5.8,
                2088,
                "Saferoads Pty Ltd",
                "Austroads TCU - HV2",
                "https://austroads.gov.au/__data/assets/pdf_file/0021/463440/211201-TCU-HV2-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1xejQnex0FC1FAkh_9XYnIbSJpu8JzLEr/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "ArmorZone MASH",
                "ArmorZone MASH Water Filled Safety Barrier System - Temporary",
                "MASH TL-1",
                "Plastic Water Filled",
                "NA",
                null,
                "Nil",
                50,
                0.44999999999999973,
                50,
                2.16,
                2.61,
                0.1,
                2,
                496,
                "Ingal Civil Products",
                "Austroads TCU - ArmorZone",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/388283/201120-TCU-ARMORZONE-MASH-Water-Filled-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1Ts5JATyX2f5c3vzSMuRGIJ2oYpjW5HS0/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "ArmorZone MASH",
                "ArmorZone MASH Water Filled Safety Barrier System - Temporary",
                "MASH TL-2",
                "Plastic Water Filled",
                "NA",
                null,
                "Nil",
                70,
                0.45,
                50,
                4.1,
                4.6,
                0.1,
                2,
                496,
                "Ingal Civil Products",
                "Austroads TCU - ArmorZone",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/388283/201120-TCU-ARMORZONE-MASH-Water-Filled-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1Ts5JATyX2f5c3vzSMuRGIJ2oYpjW5HS0/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Ricochet",
                "RICOCHET Plastic Water Filled Safety Barrier System - Temporary",
                "MASH TL-1",
                "Plastic Water Filled",
                "NA",
                null,
                "Nil",
                50,
                0.5800000000000001,
                45,
                2.28,
                2.86,
                0.1,
                2,
                580,
                "TFH Hire Services",
                "Austroads TCU - Ricochet",
                "https://austroads.gov.au/__data/assets/pdf_file/0027/388323/201120-TCU-RICOCHET-Water-Filled-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1PNpkeha4poSklatnF9R0PPsIUSPEfndo/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Lo-Ro Water Cable Barrier",
                "Lo-Ro Water Filled Cable Barrier System - Temporary ",
                "MASH TL-1",
                "Plastic Water Filled",
                "freestanding",
                null,
                "Nil",
                50,
                0.57,
                48,
                1.8,
                2.3,
                0.1,
                1.92,
                688,
                "Jaybro Group Pty Ltd",
                "Austroads TCU - Lo-Ro",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/388320/201120-TCU-LO-RO-Water-Cable-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/148RTU-MtWa9wMSmVJsb6hulGv6uDoOmL/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Lo-Ro Water Cable Barrier",
                "Lo-Ro Water Filled Cable Barrier System - Temporary ",
                "MASH TL-2",
                "Plastic Water Filled",
                "freestanding",
                null,
                "Nil",
                70,
                0.57,
                48,
                3.6,
                4.1,
                0.1,
                1.92,
                688,
                "Jaybro Group Pty Ltd",
                "Austroads TCU - Lo-Ro",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/388320/201120-TCU-LO-RO-Water-Cable-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/148RTU-MtWa9wMSmVJsb6hulGv6uDoOmL/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Shield I",
                "SHIELD I Water Filled Safety Barrier System - Temporary ",
                "MASH TL-1",
                "Plastic Water Filled",
                "freestanding",
                null,
                "Nil",
                50,
                0.5999999999999996,
                52,
                2.2,
                2.8,
                0.05,
                2.2,
                611,
                "National Plastic Group",
                "Austroads TCU - Shield I",
                "https://austroads.gov.au/__data/assets/pdf_file/0030/388326/201120-TCU-SHIELD-I-Water-Filled-Barrier-System-Temporary.pdf",
                "https://drive.google.com/file/d/1xW0lqDpWlswA80-4eE983vn0uXsR3n6K/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Mobile Barriers MBT-1",
                "MOBILE BARRIER MBT-1 Steel Safety Barrier - Temporary ",
                "MASH TL-3",
                "Mobile Workzone",
                "NA",
                null,
                "Nil",
                80,
                0.61,
                30.5,
                0.61,
                1.22,
                0.07,
                "12.8, 18.9",
                "9000, 38500",
                "Mobile Barriers",
                "Austroads TCU - MBT-1",
                "https://austroads.gov.au/__data/assets/pdf_file/0025/388321/201120-TCU-MBT-1-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1seE4XAzVwSerP0X0INvohmuAGIy68teo/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Rebloc 80SAH 12",
                "Rebloc 80SAH_12 Safety Barrier - Temporary",
                "MASH TL-3",
                "Concrete Freestanding",
                "Anchored at ends only",
                null,
                "Nil",
                100,
                0.3,
                108,
                1.31,
                1.56,
                0.1,
                12,
                3270,
                "Onsite",
                "Austroads TCU - Rebloc",
                "https://austroads.gov.au/__data/assets/pdf_file/0015/515130/220902-TCU-Rebloc-80SAH_12-Safety-Barrier.pdf",
                "https://drive.google.com/file/d/1BnkQoeUW_x0UhJTi2RFMr6IRiSOGc2gh/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Rebloc 80SAH 12",
                "Rebloc 80SAH_12 Safety Barrier - Temporary",
                "MASH TL-4",
                "Concrete Freestanding",
                "Anchored at ends only",
                null,
                "Nil",
                100,
                0.3,
                156,
                1.7,
                3.23,
                0.1,
                12,
                3270,
                "Onsite",
                "Austroads TCU - Rebloc",
                "https://austroads.gov.au/__data/assets/pdf_file/0015/515130/220902-TCU-Rebloc-80SAH_12-Safety-Barrier.pdf",
                "https://drive.google.com/file/d/1BnkQoeUW_x0UhJTi2RFMr6IRiSOGc2gh/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Rebloc 80SAH 12 8B",
                "Rebloc 80SAH_12_8B Safety Barrier - Temporary",
                "MASH TL-3",
                "Concrete Anchored",
                4,
                "HSB 20 x 300mm screw bolt ",
                "Nil",
                100,
                0.3,
                60,
                0.3,
                0.6,
                0.1,
                12,
                3270,
                "Onsite",
                "Austroads TCU - Rebloc",
                "https://austroads.gov.au/__data/assets/pdf_file/0027/481626/220322-TCU-Rebloc-80SAH_12_8B-Safety-Barrier.pdf",
                "https://drive.google.com/file/d/1R9GLFNljmj_YqGtuOK3ZsajYkLTHDH8i/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Rebloc 80SAH 4",
                "Rebloc 80SAH_4 Safety Barrier - Temporary ",
                "MASH TL-3 ",
                "Concrete Freestanding",
                "Anchored at ends only",
                null,
                "Nil",
                100,
                0.30000000000000004,
                109,
                1.21,
                1.51,
                0.1,
                4.03,
                1110,
                "Onsite",
                "Austroads TCU - Rebloc",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/533576/221201-TCU-Rebloc-80SAH_4-Safety-Barrier-Temporary.pdf",
                "https://drive.google.com/file/d/1SrR9hEsesKqx5UriGXw7bsDJgDOUefHz/view?usp=sharing",
                null,
                null,
                null,
                null
            ],
            [
                "Rebloc 120FA 6 SF",
                "Rebloc 120FA_6_SF Safety Barrier - Temporary",
                "MASH TL-3",
                "Concrete Freestanding",
                "Anchored at ends only",
                null,
                "Max 80 km/h",
                100,
                0.62,
                102,
                0.4,
                1,
                0.1,
                6,
                4780,
                "Onsite",
                "Austroads TCU - Rebloc",
                "https://austroads.gov.au/__data/assets/pdf_file/0043/498778/220616-TCU-Rebloc-120FA_6_FS-Safety-Barrier.pdf",
                "https://drive.google.com/file/d/1A_h5uprcVqwsF95nHRsFxNmmboe7L6Gn/view?usp=sharing",
                null,
                null,
                "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.",
                null
            ],
            [
                "Rebloc 120FA 6 SF",
                "Rebloc 120FA_6_SF Safety Barrier - Temporary",
                "MASH TL-5",
                "Concrete Freestanding",
                "Anchored at ends only",
                null,
                null,
                100,
                0.62,
                102,
                1.58,
                2.29,
                0.1,
                6,
                4780,
                "Onsite",
                "Austroads TCU - Rebloc",
                "https://austroads.gov.au/__data/assets/pdf_file/0043/498778/220616-TCU-Rebloc-120FA_6_FS-Safety-Barrier.pdf",
                "https://drive.google.com/file/d/1A_h5uprcVqwsF95nHRsFxNmmboe7L6Gn/view?usp=sharing",
                null,
                null,
                null,
                null
            ]
        ],
        "End treatment": [
            [
                "End Treatment System",
                "Product Name",
                "Accepted Test Level",
                "Type",
                "Anchor/Post Spacing (m)",
                "Post/Pin Type",
                "TMR Conditions (Speed)",
                "Test Speed (km/h)",
                "Width of system (m)",
                "Tested Article Length (m) ",
                "Deflection (m)",
                "Working Width (m)",
                "Side slope limit",
                "Registered Supplier",
                "Austroads TCU Link",
                "Manufacturers Specifications",
                "TMR Conditions"
            ],
            [
                "Absorb-M",
                "Absorb-M Plastic Crash Cushion",
                "MASH TL-2 ",
                "Water Filled, Non-Redirective, Gating Plastic Terminal",
                "Freestanding",
                "N/A",
                "Max 60 km/h ",
                60,
                0.67,
                5.29,
                "N/A (Gating)",
                "N/A",
                0.1,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0031/425587/210607-TCU-ABSORB-M-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1FZ55JffSGO1zGWxZTiBZSr7tZ2v_TA1W/view?usp=sharing",
                "Nil."
            ],
            [
                "Absorb-M",
                "Absorb-M Plastic Crash Cushion",
                "MASH TL-3",
                "Water Filled, Non-Redirective, Gating Plastic Terminal",
                "Freestanding",
                "N/A",
                "Max 80 km/h ",
                80,
                0.67,
                7.22,
                "N/A (Gating)",
                "N/A",
                0.1,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0031/425587/210607-TCU-ABSORB-M-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1FZ55JffSGO1zGWxZTiBZSr7tZ2v_TA1W/view?usp=sharing",
                "Nil."
            ],
            [
                "ArmorBuffa",
                "ArmorBuffa Plastic Water Filled Crash Cushion",
                "MASH TL-3",
                "Non-Redirective, Gating Plastic Water Filled End Treatment",
                "Freestanding",
                "N/A",
                "Max 80 km/h (TL-3)",
                80,
                0.46,
                9.313,
                "N/A (Gating)",
                "N/A",
                0.1,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/444291/210903-TCU-ArmorBuffa-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1XMeu4A57SUpPbLaY-1P7bOvFBNQSjf_T/view?usp=sharing",
                "Nil."
            ],
            [
                "ArmorBuffa",
                "ArmorBuffa Plastic Water Filled Crash Cushion",
                "MASH TL-2",
                "Non-Redirective, Gating Plastic Water Filled End Treatment",
                "Freestanding",
                "N/A",
                "Max 70 km/h (TL-2)",
                70,
                0.46,
                5.31,
                null,
                null,
                null,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/444291/210903-TCU-ArmorBuffa-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1XMeu4A57SUpPbLaY-1P7bOvFBNQSjf_T/view?usp=sharing",
                "Nil."
            ],
            [
                "SLED",
                "SLED Plastic Water Filled End Terminal",
                "MASH TL-1",
                "Non-Redirective, Gating Plastic Water Filled End Treatment",
                "Freestanding",
                "N/A",
                "Max 50 km/h (TL-1)",
                50,
                0.7,
                3.85,
                "N/A (Gating)",
                "N/A",
                0.1,
                "Saferoads Pty Ltd",
                "https://austroads.gov.au/__data/assets/pdf_file/0022/391261/201205-TCU-SLED-Water-Filled-End-Terminal.pdf",
                "https://drive.google.com/file/d/1Xiw9-Iq6mzLj3DT0r5d-ywnETOk3_4FY/view?usp=sharing",
                "Nil."
            ],
            [
                "SLED",
                "SLED Plastic Water Filled End Terminal",
                "MASH TL-2",
                "Non-Redirective, Gating Plastic Water Filled End Treatment",
                "Freestanding",
                "N/A",
                "Max 70 km/h (TL-2)",
                70,
                0.7,
                5.77,
                "N/A (Gating)",
                "N/A",
                0.1,
                "Saferoads Pty Ltd",
                "https://austroads.gov.au/__data/assets/pdf_file/0022/391261/201205-TCU-SLED-Water-Filled-End-Terminal.pdf",
                "https://drive.google.com/file/d/1Xiw9-Iq6mzLj3DT0r5d-ywnETOk3_4FY/view?usp=sharing",
                "Nil."
            ],
            [
                "SLED",
                "SLED Plastic Water Filled End Terminal",
                "MASH TL-3",
                "Non-Redirective, Gating Plastic Water Filled End Treatment",
                "Freestanding",
                "N/A",
                "Max 80 km/h (TL-3)",
                80,
                0.7,
                7.92,
                "N/A (Gating)",
                "N/A",
                0.1,
                "Saferoads Pty Ltd",
                "https://austroads.gov.au/__data/assets/pdf_file/0022/391261/201205-TCU-SLED-Water-Filled-End-Terminal.pdf",
                "https://drive.google.com/file/d/1Xiw9-Iq6mzLj3DT0r5d-ywnETOk3_4FY/view?usp=sharing",
                "Nil."
            ],
            [
                "Universal TAU-M",
                "Universal TAU-M Crash Cushion",
                "MASH TL-2 ",
                "Redirective Crash Cushion",
                "Refer to Drawings",
                "Refer to Drawings",
                70,
                70,
                0.76,
                4.33,
                "Redirective",
                "Redirective",
                0.08,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/633386/240307-TCU-Universal-Tau-M-Crash-Cushion-Permanent-and-Temporary.pdf",
                "https://drive.google.com/file/d/1ibyoMMWi2NxCsLgRkkQcnYcCUugYy3-e/view?usp=sharing",
                "Nil."
            ],
            [
                "Universal TAU-M",
                "Universal TAU-M Crash Cushion",
                "MASH TL-3",
                "Redirective Crash Cushion",
                "Refer to Drawings",
                "Refer to Drawings",
                100,
                100,
                0.76,
                6.93,
                "Redirective",
                "Redirective",
                0.08,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0029/633386/240307-TCU-Universal-Tau-M-Crash-Cushion-Permanent-and-Temporary.pdf",
                "https://drive.google.com/file/d/1ibyoMMWi2NxCsLgRkkQcnYcCUugYy3-e/view?usp=sharing",
                "Nil."
            ],
            [
                "TAU-XR",
                "TAU-XR Crash Cushion",
                "MASH TL-3",
                "Redirective Crash Cushion",
                "Refer to Drawings",
                "Refer to Drawings",
                "100 km/h",
                100,
                0.91,
                7.18,
                "Redirective",
                "Redirective",
                0.08,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0027/674910/240904-TCU-Tau-XR-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1mzfEKLJqgOfMsAXKj9cBqWwjZNGt1yCN/view?usp=sharing",
                "Nil."
            ],
            [
                "ET-SS",
                "ET-SS Guardrail End Terminal",
                "MASH TL-2 ",
                "Gating Terminal",
                1.905,
                "Driven or Baseplate",
                "70 km/h",
                70,
                0.45,
                7.9,
                "Gating",
                "Gating",
                0.1,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/533849/221201-TCU-ET-SS-Terminal.pdf",
                "https://drive.google.com/file/d/13K6z98rqDTeiO0zt8OiWAz_9va4_yXd6/view?usp=sharing",
                "Refer to TCU."
            ],
            [
                "ET-SS",
                "ET-SS Guardrail End Terminal",
                "MASH TL-3",
                "Gating Terminal",
                1.905,
                null,
                "100 km/h",
                100,
                0.45,
                15.48,
                "Gating",
                "Gating",
                0.1,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/533849/221201-TCU-ET-SS-Terminal.pdf",
                "https://drive.google.com/file/d/13K6z98rqDTeiO0zt8OiWAz_9va4_yXd6/view?usp=sharing",
                null
            ],
            [
                "MSKT",
                "MASH Sequential Kinking Terminal (MSKT)",
                "MASH TL-2",
                "Gating Terminal",
                1.905,
                "Driven",
                70,
                70,
                0.51,
                9.5,
                "Gating",
                "Gating",
                0.1,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0027/633375/240307-TCU-MSKT-Permanent.pdf",
                "https://drive.google.com/file/d/1YFqXazu7cxIF4S0n6ipaXOOHmPFyRj3I/view?usp=sharing",
                "Nil."
            ],
            [
                "MSKT",
                "MASH Sequential Kinking Terminal (MSKT)",
                "MASH TL-3",
                null,
                1.905,
                null,
                100,
                100,
                0.51,
                14.29,
                "Gating",
                "Gating",
                0.1,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0027/633375/240307-TCU-MSKT-Permanent.pdf",
                "https://drive.google.com/file/d/1YFqXazu7cxIF4S0n6ipaXOOHmPFyRj3I/view?usp=sharing",
                null
            ],
            [
                "MAX-Tension",
                "MAX-Tension Guardrail Terminal",
                "MASH TL-2",
                "Gating Terminal",
                1.905,
                "Driven or Baseplate",
                70,
                70,
                0.44,
                9.12,
                "Gating",
                "Gating",
                0.07,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/388247/201120-TCU-MAX-TENSION-Terminal.pdf",
                "https://drive.google.com/file/d/1NzEl1OWyiyhKfgG1YtUxzwMK37ZuHcjU/view?usp=sharing",
                "Nil."
            ],
            [
                "MAX-Tension",
                "MAX-Tension Guardrail Terminal",
                "MASH TL-3",
                null,
                1.905,
                "Driven or Baseplate",
                100,
                100,
                0.44,
                16.77,
                "Gating",
                "Gating",
                0.07,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/388247/201120-TCU-MAX-TENSION-Terminal.pdf",
                "https://drive.google.com/file/d/1NzEl1OWyiyhKfgG1YtUxzwMK37ZuHcjU/view?usp=sharing",
                null
            ],
            [
                "Trend Median Terminal",
                "Trend Median Terminal",
                "MASH TL-3",
                "Gating Terminal (Median)",
                1.905,
                "Driven",
                "100 km/h",
                100,
                0.73,
                11.1,
                "Gating",
                "Gating",
                0.1,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/554855/230324-TCU-Trend-Median-Terminal.pdf",
                "https://drive.google.com/file/d/1WvlZui1G65iPq9xgH78fTmyTYGEi83wA/view?usp=sharing",
                "Nil."
            ],
            [
                "QUADGUARD M10",
                "QuadGuard M10 Crash Cushion",
                "MASH TL-2",
                "Redirective Crash Cushion",
                "N/A",
                "Refer to Drawings",
                70,
                70,
                0.61,
                4,
                "Redirective",
                "Redirective",
                0.08,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/406958/210304-TCU-QUADGUARD-M10-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1JRQWstGayd8QDaNqFmulJW9TZkPADdf1/view?usp=sharing",
                "Nil."
            ],
            [
                "QUADGUARD M10",
                "QuadGuard M10 Crash Cushion",
                "MASH TL-3",
                "Redirective Crash Cushion",
                "N/A",
                "Refer to Drawings",
                100,
                100,
                1.755,
                6.71,
                "Redirective",
                "Redirective",
                0.08,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0032/406958/210304-TCU-QUADGUARD-M10-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1JRQWstGayd8QDaNqFmulJW9TZkPADdf1/view?usp=sharing",
                null
            ],
            [
                "QUADGUARD M10 CZ",
                "QUADGUARD M10 CZ Crash Cushion",
                "MASH TL-2",
                "Redirective Crash Cushion",
                null,
                "Refer to Drawings",
                70,
                70,
                0.61,
                4,
                "Redirective",
                "Redirective",
                0.08,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0019/444331/210906-TCU-QUADGUARD-M10-CZ-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1JRQWstGayd8QDaNqFmulJW9TZkPADdf1/view?usp=sharing",
                null
            ],
            [
                "QUADGUARD M10 CZ",
                "QUADGUARD M10 CZ Crash Cushion",
                "MASH TL-3",
                "Redirective Crash Cushion",
                null,
                "Refer to Drawings",
                100,
                100,
                0.61,
                6.71,
                "Redirective",
                "Redirective",
                null,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0019/444331/210906-TCU-QUADGUARD-M10-CZ-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1JRQWstGayd8QDaNqFmulJW9TZkPADdf1/view?usp=sharing",
                null
            ],
            [
                "QUADGUARD Elite M10",
                "QuadGuard Elite M10 Crash Cushion",
                "MASH TL-3",
                "Redirective Crash Cushion",
                "N/A",
                "Anchored",
                100,
                100,
                "0.61 (Standard) / 1.75 (Wide)",
                8.3,
                "Redirective",
                "Redirective",
                0.08,
                "Ingal Civil Products",
                "https://austroads.gov.au/__data/assets/pdf_file/0030/633378/240307-TCU-Quadguard-Elite-M10-Crash-Cushion-Permanent.pdf",
                "https://drive.google.com/file/d/145S4gU4vPa24odg_tGvOG_Dl1EMcFuj-/view?usp=sharing",
                "Nil."
            ],
            [
                "SMART Crash Cushion",
                "Smart Cushion SCI100GM",
                "MASH TL-2",
                "Redirective Crash Cushion",
                "N/A",
                "Anchored",
                70,
                70,
                0.61,
                4.2,
                "Redirective",
                "Redirective",
                0.08,
                "LB Australia",
                "https://austroads.gov.au/__data/assets/pdf_file/0024/391236/201205-TCU-SMART-Steel-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1_36wbLHK4LcrWe-D9eN0ibK73JRxbt2W/view?usp=sharing",
                "Nil."
            ],
            [
                "SMART Crash Cushion",
                "Smart Cushion SCI100GM",
                "MASH TL-3",
                "Redirective Crash Cushion",
                "N/A",
                "Anchored",
                100,
                100,
                0.61,
                6.6,
                "Redirective",
                "Redirective",
                0.08,
                null,
                "https://austroads.gov.au/__data/assets/pdf_file/0024/391236/201205-TCU-SMART-Steel-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1_36wbLHK4LcrWe-D9eN0ibK73JRxbt2W/view?usp=sharing",
                null
            ],
            [
                "Hercules",
                "Hercules Crash Cushion",
                "MASH TL-3",
                "Redirective Crash Cushion",
                "N/A",
                "Anchored",
                "100 km/h",
                100,
                0.59,
                5.83,
                "Redirective",
                "Redirective",
                0.08,
                "Safe Direction",
                "https://austroads.gov.au/__data/assets/pdf_file/0022/444289/210903-TCU-Hercules-Crash-Cushion.pdf",
                "https://drive.google.com/file/d/1SfvSsfdRiD1n3AlI_LepNQltOJhjzRGJ/view?usp=sharing",
                "Nil."
            ]
        ]
    }
};
